import "./logic/logic.js"
import "./styles.css"
import "./ui/renderProject.js"
import "./controllers/projectController.js"
import "./controllers/todoController.js"
import "./ui/renderTodo.js"
import "./controllers/taskController.js"
import "./ui/renderTask.js"